version: "2"
output:
  formats:
    text:
      path: stdout
linters:
  default: none
  enable:
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - revive
  settings:
    gocyclo:
      min-complexity: 20
    revive:
      rules:
        - name: package-comments
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*.pb.go
      - .*_mock.go
      - .*_test.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*.pb.go
      - .*_mock.go
      - .*_test.go
      - third_party$
      - builtin$
      - examples$
