//
// Tencent is pleased to support the open source community by making
// trpc-agent-go available.
//
// Copyright (C) 2025 Tencent.  All rights reserved.
//
// trpc-agent-go is licensed under the Apache License Version 2.0.
//
//

// Package main prints the model input generated by a Swarm Team handoff.
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"strings"

	"github.com/google/uuid"

	"trpc.group/trpc-go/trpc-agent-go/model"
)

func main() {
	flag.Parse()
	cfg := configFromFlags()
	if cfg.Input == "" {
		log.Fatal("input is empty")
	}
	runnerInstance, err := buildRunner(cfg)
	if err != nil {
		log.Fatalf("build runner: %v", err)
	}
	defer runnerInstance.Close()
	ctx, cancel := context.WithTimeout(context.Background(), cfg.Timeout)
	defer cancel()
	sessionID := sessionPrefix + uuid.NewString()
	fmt.Printf("Session: %s\n", sessionID)
	fmt.Printf("Model: %s\n", cfg.ModelName)
	fmt.Printf("Mock: %t\n", cfg.MockMode)
	fmt.Printf("Streaming: %t\n", cfg.Streaming)
	fmt.Printf("Child isolated: %t\n", cfg.ChildIsolated)
	fmt.Printf("Rewrite child input: %t\n", cfg.RewriteChildInput)
	fmt.Printf("Input: %s\n", cfg.Input)
	fmt.Println(strings.Repeat("=", 80))
	events, err := runnerInstance.Run(ctx, userID, sessionID, model.NewUserMessage(cfg.Input))
	if err != nil {
		log.Fatalf("run swarm: %v", err)
	}
	if err := printEvents(events, cfg.ContentLimit); err != nil {
		log.Fatalf("print events: %v", err)
	}
	if ctx.Err() != nil {
		log.Fatalf("run context ended: %v", ctx.Err())
	}
}
